version: '3.8'

services:
  app:
    build: .
    container_name: hello_app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: hello_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
